var clearName = {
   "Afghanistan":"Afghanistan",
   "Albania":"Albania",
   "Algeria":"Algeria",
   "Andorra":"Andorra",
   "Angola":"Angola",
   "Antigua and Barbuda":"Antigua and Barbuda",
   "Argentina":"Argentina",
   "Armenia":"Armenia",
   "Australia":"Australia",
   "Austria":"Austria",
   "Azerbaijan":"Azerbaijan",
   "Bahamas":"Bahamas",
   "Bahrain":"Bahrain",
   "Bangladesh":"Bangladesh",
   "Barbados":"Barbados",
   "Belarus":"Belarus",
   "Belgium":"Belgium",
   "Belize":"Belize",
   "Benin":"Benin",
   "Bhutan":"Bhutan",
   "Bolivia":"Bolivia",
   "Bosnia and Herzegovina":"Bosnia and Herzegovina",
   "Botswana":"Botswana",
   "Brazil":"Brazil",
   "Brunei Darussalam":"Brunei Darussalam",
   "Bulgaria":"Bulgaria",
   "Burkina Faso":"Burkina Faso",
   "Burundi":"Burundi",
   "Cambodia":"Cambodia",
   "Cameroon":"Cameroon",
   "Canada":"Canada",
   "Cape Verde":"Cape Verde",
   "Central African Republic":"Central African Republic",
   "Chad":"Chad",
   "Chile":"Chile",
   "China":"China",
   "Colombia":"Colombia",
   "Comoros":"Comoros",
   "Congo (Brazzaville)":"Congo (Brazzaville)",
   "Congo (Kinshasa)":"Congo (Kinshasa)",
   "Costa Rica":"Costa Rica",
   "Croatia":"Croatia",
   "Cuba":"Cuba",
   "Cyprus":"Cyprus",
   "Czech Republic":"Czech Republic",
   "Côte d'Ivoire":"Côte d'Ivoire",
   "Denmark":"Denmark",
   "Djibouti":"Djibouti",
   "Dominica":"Dominica",
   "Dominican Republic":"Dominican Republic",
   "Ecuador":"Ecuador",
   "Egypt":"Egypt",
   "El Salvador":"El Salvador",
   "Equatorial Guinea":"Equatorial Guinea",
   "Eritrea":"Eritrea",
   "Estonia":"Estonia",
   "Ethiopia":"Ethiopia",
   "Fiji":"Fiji",
   "Finland":"Finland",
   "France":"France",
   "Gabon":"Gabon",
   "Gambia":"Gambia",
   "Georgia":"Georgia",
   "Germany":"Germany",
   "Ghana":"Ghana",
   "Greece":"Greece",
   "Grenada":"Grenada",
   "Guatemala":"Guatemala",
   "Guinea":"Guinea",
   "Guinea-Bissau":"Guinea-Bissau",
   "Guyana":"Guyana",
   "Haiti":"Haiti",
   "Holy See (Vatican City State)":"Vatican City",
   "Honduras":"Honduras",
   "Hungary":"Hungary",
   "Iceland":"Iceland",
   "India":"India",
   "Indonesia":"Indonesia",
   "Iran, Islamic Republic of":"Iran",
   "Iraq":"Iraq",
   "Ireland":"Ireland",
   "Israel":"Israel",
   "Italy":"Italy",
   "Jamaica":"Jamaica",
   "Japan":"Japan",
   "Jordan":"Jordan",
   "Kazakhstan":"Kazakhstan",
   "Kenya":"Kenya",
   "Korea (South)":"S. Korea",
   "Kuwait":"Kuwait",
   "Kyrgyzstan":"Kyrgyzstan",
   "Lao PDR":"Lao PDR",
   "Latvia":"Latvia",
   "Lebanon":"Lebanon",
   "Lesotho":"Lesotho",
   "Liberia":"Liberia",
   "Libya":"Libya",
   "Liechtenstein":"Liechtenstein",
   "Lithuania":"Lithuania",
   "Luxembourg":"Luxembourg",
   "Macao, SAR China":"Macao",
   "Macedonia, Republic of":"Macedonia",
   "Madagascar":"Madagascar",
   "Malawi":"Malawi",
   "Malaysia":"Malaysia",
   "Maldives":"Maldives",
   "Mali":"Mali",
   "Malta":"Malta",
   "Marshall Islands":"Marshall Islands",
   "Mauritania":"Mauritania",
   "Mauritius":"Mauritius",
   "Mexico":"Mexico",
   "Moldova":"Moldova",
   "Monaco":"Monaco",
   "Mongolia":"Mongolia",
   "Montenegro":"Montenegro",
   "Morocco":"Morocco",
   "Mozambique":"Mozambique",
   "Myanmar":"Myanmar",
   "Namibia":"Namibia",
   "Nepal":"Nepal",
   "Netherlands":"Netherlands",
   "New Zealand":"New Zealand",
   "Nicaragua":"Nicaragua",
   "Niger":"Niger",
   "Nigeria":"Nigeria",
   "Norway":"Norway",
   "Oman":"Oman",
   "Pakistan":"Pakistan",
   "Palestinian Territory":"Palestinian Territory",
   "Panama":"Panama",
   "Papua New Guinea":"Papua New Guinea",
   "Paraguay":"Paraguay",
   "Peru":"Peru",
   "Philippines":"Philippines",
   "Poland":"Poland",
   "Portugal":"Portugal",
   "Qatar":"Qatar",
   "Republic of Kosovo":"Kosovo",
   "Romania":"Romania",
   "Russian Federation":"Russia",
   "Rwanda":"Rwanda",
   "Réunion":"Réunion",
   "Saint Kitts and Nevis":"Saint Kitts and Nevis",
   "Saint Lucia":"Saint Lucia",
   "Saint Vincent and Grenadines":"Saint Vincent and Grenadines",
   "Samoa":"Samoa",
   "San Marino":"San Marino",
   "Sao Tome and Principe":"Sao Tome and Principe",
   "Saudi Arabia":"Saudi Arabia",
   "Senegal":"Senegal",
   "Serbia":"Serbia",
   "Seychelles":"Seychelles",
   "Sierra Leone":"Sierra Leone",
   "Singapore":"Singapore",
   "Slovakia":"Slovakia",
   "Slovenia":"Slovenia",
   "Solomon Islands":"Solomon Islands",
   "Somalia":"Somalia",
   "South Africa":"South Africa",
   "South Sudan":"South Sudan",
   "Spain":"Spain",
   "Sri Lanka":"Sri Lanka",
   "Sudan":"Sudan",
   "Suriname":"Suriname",
   "Swaziland":"Swaziland",
   "Sweden":"Sweden",
   "Switzerland":"Switzerland",
   "Syrian Arab Republic (Syria)":"Syria",
   "Taiwan, Republic of China":"Taiwan",
   "Tajikistan":"Tajikistan",
   "Tanzania, United Republic of":"Tanzania",
   "Thailand":"Thailand",
   "Timor-Leste":"Timor-Leste",
   "Togo":"Togo",
   "Trinidad and Tobago":"Trinidad and Tobago",
   "Tunisia":"Tunisia",
   "Turkey":"Turkey",
   "Uganda":"Uganda",
   "Ukraine":"Ukraine",
   "United Arab Emirates":"UAE",
   "United Kingdom":"UK",
   "United States of America":"USA",
   "Uruguay":"Uruguay",
   "Uzbekistan":"Uzbekistan",
   "Vanuatu":"Vanuatu",
   "Venezuela (Bolivarian Republic)":"Venezuela",
   "Viet Nam":"Viet Nam",
   "Western Sahara":"Western Sahara",
   "Yemen":"Yemen",
   "Zambia":"Zambia",
   "Zimbabwe":"Zimbabwe"
};

var countryInfo = {
   "Georgia":{
      "population":"4630000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Georgia.svg"
   },
   "Singapore":{
      "population":"4701069",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg"
   },
   "Germany":{
      "population":"81802257",
      "flag":"https://upload.wikimedia.org/wikipedia/en/b/ba/Flag_of_Germany.svg"
   },
   "Oman":{
      "population":"2967717",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Oman.svg"
   },
   "Costa Rica":{
      "population":"4516220",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Costa_Rica_%28state%29.svg"
   },
   "India":{
      "population":"1173108018",
      "flag":"https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg"
   },
   "Zimbabwe":{
      "population":"13061000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/6/6a/Flag_of_Zimbabwe.svg"
   },
   "Luxembourg":{
      "population":"497538",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/d/da/Flag_of_Luxembourg.svg"
   },
   "Belarus":{
      "population":"9685000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/8/85/Flag_of_Belarus.svg"
   },
   "Belgium":{
      "population":"10403000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Belgium.svg"
   },
   "Lebanon":{
      "population":"4125247",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/5/59/Flag_of_Lebanon.svg"
   },
   "Liberia":{
      "population":"3685076",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/b/b8/Flag_of_Liberia.svg"
   },
   "Estonia":{
      "population":"1291170",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/8/8f/Flag_of_Estonia.svg"
   },
   "Romania":{
      "population":"21959278",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Romania.svg"
   },
   "Brazil":{
      "population":"201103330",
      "flag":"https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg"
   },
   "Hungary":{
      "population":"9982000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg"
   },
   "Jamaica":{
      "population":"2847232",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Jamaica.svg"
   },
   "Argentina":{
      "population":"41343201",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg"
   },
   "Kenya":{
      "population":"40046566",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Kenya.svg"
   },
   "Suriname":{
      "population":"492829",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/6/60/Flag_of_Suriname.svg"
   },
   "Brunei Darussalam":{
      "population":"395027",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Brunei.svg"
   },
   "Grenada":{
      "population":"107818",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Grenada.svg"
   },
   "Mauritania":{
      "population":"3205060",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Mauritania.svg"
   },
   "Paraguay":{
      "population":"6375830",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/2/27/Flag_of_Paraguay.svg"
   },
   "Tanzania":{
      "population":"41892895"
   },
   "Gabon":{
      "population":"1545255",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/0/04/Flag_of_Gabon.svg"
   },
   "Indonesia":{
      "population":"242968342",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg"
   },
   "Malta":{
      "population":"403000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/7/73/Flag_of_Malta.svg"
   },
   "Nigeria":{
      "population":"154000000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg"
   },
   "Albania":{
      "population":"2986952",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/3/36/Flag_of_Albania.svg"
   },
   "Ecuador":{
      "population":"14790608",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/e/e8/Flag_of_Ecuador.svg"
   },
   "Bolivia":{
      "population":"9947418"
   },
   "Chile":{
      "population":"16746491",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/7/78/Flag_of_Chile.svg"
   },
   "Colombia":{
      "population":"47790000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Colombia.svg"
   },
   "Gambia":{
      "population":"1593256",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_The_Gambia.svg"
   },
   "Norway":{
      "population":"5009150",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg"
   },
   "Samoa":{
      "population":"192001",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Samoa.svg"
   },
   "Bahrain":{
      "population":"738004",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Bahrain.svg"
   },
   "Cape Verde":{
      "population":"508659",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/3/38/Flag_of_Cape_Verde.svg"
   },
   "Lithuania":{
      "population":"2944459",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Lithuania.svg"
   },
   "Andorra":{
      "population":"84000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Andorra.svg"
   },
   "Haiti":{
      "population":"9648924",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Haiti.svg"
   },
   "Algeria":{
      "population":"34586184",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Algeria.svg"
   },
   "Saint Vincent and Grenadines":{
      "population":"104217",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg"
   },
   "Sudan":{
      "population":"35000000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Sudan.svg"
   },
   "Armenia":{
      "population":"2968000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/2/2f/Flag_of_Armenia.svg"
   },
   "Dominica":{
      "population":"72813",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/c/c4/Flag_of_Dominica.svg"
   },
   "Peru":{
      "population":"29907003",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Peru.svg"
   },
   "Egypt":{
      "population":"80471869",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg"
   },
   "Rwanda":{
      "population":"11055976",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Rwanda.svg"
   },
   "Venezuela":{
      "population":"27223228"
   },
   "Guinea":{
      "population":"10324025",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/e/ed/Flag_of_Guinea.svg"
   },
   "Morocco":{
      "population":"33848242",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/2/2c/Flag_of_Morocco.svg"
   },
   "Namibia":{
      "population":"2128471",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_Namibia.svg"
   },
   "Nepal":{
      "population":"28951852",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/9b/Flag_of_Nepal.svg"
   },
   "Slovakia":{
      "population":"5455000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/e/e6/Flag_of_Slovakia.svg"
   },
   "Tajikistan":{
      "population":"7487489",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Tajikistan.svg"
   },
   "Australia":{
      "population":"21515754",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/8/88/Flag_of_Australia_%28converted%29.svg"
   },
   "Central African Republic":{
      "population":"4844927",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/6/6f/Flag_of_the_Central_African_Republic.svg"
   },
   "Macedonia":{
      "population":"2062294"
   },
   "Canada":{
      "population":"33679000",
      "flag":"https://upload.wikimedia.org/wikipedia/en/c/cf/Flag_of_Canada.svg"
   },
   "Papua New Guinea":{
      "population":"6064515",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/e/e3/Flag_of_Papua_New_Guinea.svg"
   },
   "Nicaragua":{
      "population":"5995928",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Nicaragua.svg"
   },
   "Latvia":{
      "population":"2217969",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Latvia.svg"
   },
   "Maldives":{
      "population":"395650",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/0/0f/Flag_of_Maldives.svg"
   },
   "Palestinian Territory":{
      "population":"3800000"
   },
   "Uganda":{
      "population":"33398682",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/4/4e/Flag_of_Uganda.svg"
   },
   "Israel":{
      "population":"7353985",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Israel.svg"
   },
   "Saudi Arabia":{
      "population":"25731776",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/0/0d/Flag_of_Saudi_Arabia.svg"
   },
   "Comoros":{
      "population":"773407",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/94/Flag_of_the_Comoros.svg"
   },
   "Djibouti":{
      "population":"740528",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_Djibouti.svg"
   },
   "Bahamas":{
      "population":"301790",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/93/Flag_of_the_Bahamas.svg"
   },
   "Guatemala":{
      "population":"13550440",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/e/ec/Flag_of_Guatemala.svg"
   },
   "Guyana":{
      "population":"748486",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_Guyana.svg"
   },
   "Sao Tome and Principe":{
      "population":"175808",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Sao_Tome_and_Principe.svg"
   },
   "Western Sahara":{
      "population":"273008"
   },
   "Eritrea":{
      "population":"5792984",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/2/29/Flag_of_Eritrea.svg"
   },
   "Macao":{
      "population":"449198",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/6/63/Flag_of_Macau.svg"
   },
   "Fiji":{
      "population":"875983",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/b/ba/Flag_of_Fiji.svg"
   },
   "France":{
      "population":"64768389",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931958%29.svg/1280px-Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931958%29.svg.png"
   },
   "Monaco":{
      "population":"32965",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/e/ea/Flag_of_Monaco.svg"
   },
   "Netherlands":{
      "population":"16645000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/2/20/Flag_of_the_Netherlands.svg"
   },
   "Panama":{
      "population":"3410676",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/a/ab/Flag_of_Panama.svg"
   },
   "Dominican Republic":{
      "population":"9823821",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_the_Dominican_Republic.svg"
   },
   "Portugal":{
      "population":"10676000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Portugal.svg"
   },
   "Iceland":{
      "population":"308910",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Iceland.svg"
   },
   "Russia":{
      "population":"140702000"
   },
   "Yemen":{
      "population":"23495361",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Yemen.svg"
   },
   "Congo (Brazzaville)":{
      "population":"3039126"
   },
   "Timor-Leste":{
      "population":"1154625",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/2/26/Flag_of_East_Timor.svg"
   },
   "Réunion":{
      "population":"776948",
      "flag":"https://upload.wikimedia.org/wikipedia/en/c/c3/Flag_of_France.svg"
   },
   "Sweden":{
      "population":"9828655",
      "flag":"https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg"
   },
   "Taiwan":{
      "population":"22894384",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/7/72/Flag_of_the_Republic_of_China.svg"
   },
   "Guinea-Bissau":{
      "population":"1565126",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/0/01/Flag_of_Guinea-Bissau.svg"
   },
   "Mauritius":{
      "population":"1294104",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/7/77/Flag_of_Mauritius.svg"
   },
   "New Zealand":{
      "population":"4252277",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg"
   },
   "Denmark":{
      "population":"5484000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg"
   },
   "Malawi":{
      "population":"15447500",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/d/d1/Flag_of_Malawi.svg"
   },
   "Thailand":{
      "population":"67089500",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg"
   },
   "Ukraine":{
      "population":"45415596",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/4/49/Flag_of_Ukraine.svg"
   },
   "Uzbekistan":{
      "population":"27865738",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/8/84/Flag_of_Uzbekistan.svg"
   },
   "Mali":{
      "population":"13796354",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_Mali.svg"
   },
   "Marshall Islands":{
      "population":"65859",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/2/2e/Flag_of_the_Marshall_Islands.svg"
   },
   "Mongolia":{
      "population":"3086918",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/4/4c/Flag_of_Mongolia.svg"
   },
   "Angola":{
      "population":"13068161",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/9d/Flag_of_Angola.svg"
   },
   "Switzerland":{
      "population":"7581000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/0/08/Flag_of_Switzerland_%28Pantone%29.svg"
   },
   "Viet Nam":{
      "population":"89571130",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_Vietnam.svg"
   },
   "Botswana":{
      "population":"2029307",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_Botswana.svg"
   },
   "Somalia":{
      "population":"10112453",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/a/a0/Flag_of_Somalia.svg"
   },
   "China":{
      "population":"1330044000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/fa/Flag_of_the_People%27s_Republic_of_China.svg"
   },
   "Croatia":{
      "population":"4284889",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/1/1b/Flag_of_Croatia.svg"
   },
   "Sri Lanka":{
      "population":"21513990",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/1/11/Flag_of_Sri_Lanka.svg"
   },
   "Benin":{
      "population":"9056010",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/0/0a/Flag_of_Benin.svg"
   },
   "Cameroon":{
      "population":"19294149",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Cameroon.svg"
   },
   "South Africa":{
      "population":"49000000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg"
   },
   "Mexico":{
      "population":"112468855",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg"
   },
   "El Salvador":{
      "population":"6052064",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/3/34/Flag_of_El_Salvador.svg"
   },
   "Ghana":{
      "population":"24339838",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/1/19/Flag_of_Ghana.svg"
   },
   "Kazakhstan":{
      "population":"15340000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/d/d3/Flag_of_Kazakhstan.svg"
   },
   "Moldova":{
      "population":"4324000"
   },
   "South Sudan":{
      "population":"8260490"
   },
   "Barbados":{
      "population":"285653",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/e/ef/Flag_of_Barbados.svg"
   },
   "Greece":{
      "population":"11000000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_Greece.svg"
   },
   "Honduras":{
      "population":"7989415",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/c/ca/Naval_Ensign_of_Honduras.svg"
   },
   "Bangladesh":{
      "population":"156118464",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/f9/Flag_of_Bangladesh.svg"
   },
   "Chad":{
      "population":"10543464",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/4/4b/Flag_of_Chad.svg"
   },
   "Niger":{
      "population":"15878271",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/f4/Flag_of_Niger.svg"
   },
   "Philippines":{
      "population":"99900177",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg"
   },
   "Austria":{
      "population":"8205000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/4/41/Flag_of_Austria.svg"
   },
   "Ireland":{
      "population":"4622917",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/4/45/Flag_of_Ireland.svg"
   },
   "Jordan":{
      "population":"6407085",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/c/c0/Flag_of_Jordan.svg"
   },
   "Mozambique":{
      "population":"22061451",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/d/d0/Flag_of_Mozambique.svg"
   },
   "Senegal":{
      "population":"12323252",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/fd/Flag_of_Senegal.svg"
   },
   "Italy":{
      "population":"60340328",
      "flag":"https://upload.wikimedia.org/wikipedia/en/0/03/Flag_of_Italy.svg"
   },
   "Poland":{
      "population":"38500000",
      "flag":"https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg"
   },
   "Turkey":{
      "population":"77804122",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg"
   },
   "Uruguay":{
      "population":"3477000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Uruguay.svg"
   },
   "Swaziland":{
      "population":"1354051",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/fb/Flag_of_Eswatini.svg"
   },
   "Cuba":{
      "population":"11423000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/b/bd/Flag_of_Cuba.svg"
   },
   "Iran":{
      "population":"76923300",
      "flag":" https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg"
   },
   "Bosnia and Herzegovina":{
      "population":"4590000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/b/bf/Flag_of_Bosnia_and_Herzegovina.svg"
   },
   "Kyrgyzstan":{
      "population":"5776500",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/c/c7/Flag_of_Kyrgyzstan.svg"
   },
   "Myanmar":{
      "population":"53414374",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/8/8c/Flag_of_Myanmar.svg"
   },
   "Togo":{
      "population":"6587239",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/6/68/Flag_of_Togo.svg"
   },
   "Bhutan":{
      "population":"699847",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/91/Flag_of_Bhutan.svg"
   },
   "Montenegro":{
      "population":"666730",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Montenegro.svg"
   },
   "Congo (Kinshasa)":{
      "population":"70916439",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/92/Flag_of_the_Republic_of_the_Congo.svg"
   },
   "Czech Republic":{
      "population":"10476000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg"
   },
   "Kosovo":{
      "population":"1800000"
   },
   "UAE":{
      "population":"4975593",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg"
   },
   "Belize":{
      "population":"314522",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/e/e7/Flag_of_Belize.svg"
   },
   "Equatorial Guinea":{
      "population":"1014999",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Equatorial_Guinea.svg"
   },
   "Lao PDR":{
      "population":"6368162",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/5/56/Flag_of_Laos.svg"
   },
   "Qatar":{
      "population":"840926",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/6/65/Flag_of_Qatar.svg"
   },
   "Burundi":{
      "population":"9863117",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/5/50/Flag_of_Burundi.svg"
   },
   "Cyprus":{
      "population":"1102677",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_Cyprus.svg"
   },
   "Vatican City":{
      "population":"921",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/0/00/Flag_of_the_Vatican_City.svg"
   },
   "Malaysia":{
      "population":"28274729",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg"
   },
   "San Marino":{
      "population":"31477",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/b/b1/Flag_of_San_Marino.svg"
   },
   "Solomon Islands":{
      "population":"559198",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/7/74/Flag_of_the_Solomon_Islands.svg"
   },
   "Cambodia":{
      "population":"14453680",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/8/83/Flag_of_Cambodia.svg"
   },
   "Finland":{
      "population":"5244000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Finland.svg"
   },
   "Spain":{
      "population":"46505963",
      "flag":"https://upload.wikimedia.org/wikipedia/en/9/9a/Flag_of_Spain.svg"
   },
   "Trinidad and Tobago":{
      "population":"1228691",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/6/64/Flag_of_Trinidad_and_Tobago.svg"
   },
   "UK":{
      "population":"62348447",
      "flag":"https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg"
   },
   "Syria":{
      "population":"22198110",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/5/53/Flag_of_Syria.svg"
   },
   "S. Korea":{
      "population":"48422644",
      "flag": "https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg"
   },
   "Afghanistan":{
      "population":"29121286",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Afghanistan.svg"
   },
   "Burkina Faso":{
      "population":"16241811",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/3/31/Flag_of_Burkina_Faso.svg"
   },
   "Iraq":{
      "population":"29671605",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/f6/Flag_of_Iraq.svg"
   },
   "Antigua and Barbuda":{
      "population":"86754",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/8/89/Flag_of_Antigua_and_Barbuda.svg"
   },
   "Liechtenstein":{
      "population":"35000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/4/47/Flag_of_Liechtenstein.svg"
   },
   "Saint Kitts and Nevis":{
      "population":"51134",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg"
   },
   "USA":{
      "population":"310232863",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/e/e2/Flag_of_the_United_States_%28Pantone%29.svg"
   },
   "Azerbaijan":{
      "population":"8303512",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/d/dd/Flag_of_Azerbaijan.svg"
   },
   "Ethiopia":{
      "population":"88013491",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/7/71/Flag_of_Ethiopia.svg"
   },
   "Slovenia":{
      "population":"2007000",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/f0/Flag_of_Slovenia.svg"
   },
   "Sierra Leone":{
      "population":"5245695",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/1/17/Flag_of_Sierra_Leone.svg"
   },
   "Bulgaria":{
      "population":"7148785",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/9a/Flag_of_Bulgaria.svg"
   },
   "Kuwait":{
      "population":"2789132",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/a/aa/Flag_of_Kuwait.svg"
   },
   "Lesotho":{
      "population":"1919552",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/4/4a/Flag_of_Lesotho.svg"
   },
   "Libya":{
      "population":"6461454"
   },
   "Madagascar":{
      "population":"21281844",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Madagascar.svg"
   },
   "Côte d'Ivoire":{
      "population":"21058798"
   },
   "Japan":{
      "population":"127288000",
      "flag":"https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg"
   },
   "Tunisia":{
      "population":"10589025",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/c/ce/Flag_of_Tunisia.svg"
   },
   "Pakistan":{
      "population":"184404791",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/3/32/Flag_of_Pakistan.svg"
   },
   "Serbia":{
      "population":"7344847",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/ff/Flag_of_Serbia.svg"
   },
   "Seychelles":{
      "population":"88340",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Seychelles.svg"
   },
   "Zambia":{
      "population":"13460305",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/0/06/Flag_of_Zambia.svg"
   },
   "Saint Lucia":{
      "population":"160922",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Saint_Lucia.svg"
   },
   "Vanuatu":{
      "population":"221552",
      "flag":"https://upload.wikimedia.org/wikipedia/commons/b/bc/Flag_of_Vanuatu.svg"
   }
};